# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[spec rubocop]

desc "Build parser files generated by racc"
task racc: [
  "lib/yard_to_rbs_inline_example/yard_type/parser.rb"
]

rule ".rb" => ".y" do |t|
  sh "bundle exec racc #{t.source} -o #{t.name}"
end
