# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"
require "bump/tasks"

RuboCop::RakeTask.new

task default: %i[spec rubocop steep]

desc "Build parser files generated by racc"
task racc: [
  "lib/yard_to_rbs_inline/yard_type/parser.rb"
]

desc "Build rbs files"
task rbs: ["rbs:collection", "rbs:inline"]

namespace :rbs do
  desc "Install collections"
  task :collection do
    sh "bundle exec rbs collection install"
  end

  desc "Generate RBS files"
  task inline: "rbs:inline:build"

  namespace :inline do
    desc "Generate RBS files from rbs-inline"
    task :build do
      sh "bundle exec rbs-inline lib --opt-out --output=sig/inline"
    end

    desc "Watch files to build rbs-inline"
    task :watch do
      require "listen"

      listener = Listen.to("lib", only: /\.rb$/) do
        Rake::Task["rbs:inline:build"].execute
      end
      listener.start
      sleep
    ensure
      listener&.stop
    end
  end
end

desc "Type check the code"
task steep: ["rbs:collection", "rbs:inline"] do
  sh "bundle exec steep check"
end

rule ".rb" => ".y" do |t|
  sh "bundle exec racc #{t.source} -o #{t.name}"
end
